security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            guard:
                authenticators:
                    - App\Security\Oauth2Authenticator
                    - App\Security\AppLoginAuthenticator
                entry_point: App\Security\AppLoginAuthenticator
            stateless: true
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    access_control:
         - { path: ^/user/profile, roles: ROLE_USER }
